using ERP.Share.Abstractions.Shared;

namespace ERP.Application.UseCases.HangHoa.CreateHangHoa;
public sealed record CreateHangHoaCommand(
    string MaChuan,
    string? HsCode,
    string? ThongSoKyThuat,
    string TenHang,
    Ulid? IdNhomHang,
    string DonViTinh,
    float? KhoiLuong,
    string? XuatXu,
    int? Vat,
    decimal? GiaNhap,
    decimal? GiaBan1,
    decimal? GiaBan2,
    decimal? GiaBan3,
    decimal? GiaBan4,
    decimal? GiaBan5,
    decimal? Ck1,
    decimal? Ck2,
    decimal? Ck3,
    decimal? Ck4,
    decimal? Ck5,
    string? MaChuyenDoi,
    string? GhiChu,
    string? LinkSanPham,
    string? PhuKienDiKem,
    int? SoNgayCapHang,
    bool? IsTachMa,
    string? TinhTrangHangHoa,
    string? DongSanPham,
    string MangKinhDoanh,
    decimal? GiaDaiLy,
    string? PhanLoaiHangHoa,
    string? TenHangBaoCao,
    List<string> HinhAnhs) : ICommand;
